<?php
/**
 * Certificate log admin page renderer.
 *
 * @package AlyntCertificateGenerator
 */

declare( strict_types=1 );

namespace Alynt\CertificateGenerator\AdminUi;

defined( 'ABSPATH' ) || exit;

class Alynt_Certificate_Generator_Certificate_Log_Page_Renderer {
	/**
	 * Render the log list page.
	 *
	 * @param object $list_table List table instance.
	 * @param string $export_url Export URL.
	 * @param string $notice     Success notice.
	 * @param string $error      Error notice.
	 */
	public function render_list_page( object $list_table, string $export_url, string $notice = '', string $error = '' ): void {
		echo '<div class="wrap">';
		echo '<h1>' . esc_html__( 'Certificate Logs', 'alynt-certificate-generator' ) . '</h1>';
		if ( '' !== $notice ) {
			echo '<div class="notice notice-success is-dismissible" role="status" aria-live="polite"><p>' . esc_html( $notice ) . '</p></div>';
		}
		if ( '' !== $error ) {
			echo '<div class="notice notice-error is-dismissible" role="alert"><p>' . esc_html( $error ) . '</p></div>';
		}
		echo '<hr class="wp-header-end" />';
		echo '<p>';
		echo '<a class="button" href="' . esc_url( $export_url ) . '">' . esc_html__( 'Export CSV', 'alynt-certificate-generator' ) . '</a>';
		echo '</p>';

		echo '<form method="get">';
		echo '<input type="hidden" name="page" value="alynt-certificate-logs" />';
		$list_table->display();
		echo '</form>';
		echo '</div>';
	}

	/**
	 * Render missing log message.
	 */
	public function render_missing_detail(): void {
		echo '<div class="wrap">';
		echo '<h1>' . esc_html__( 'Certificate Log Detail', 'alynt-certificate-generator' ) . '</h1>';
		echo '<hr class="wp-header-end" />';
		echo '<div class="notice notice-error is-dismissible" role="alert"><p>' . esc_html__( 'Log entry not found.', 'alynt-certificate-generator' ) . '</p></div>';
		echo '</div>';
	}

	/**
	 * Render detail view for a log entry.
	 *
	 * @param array $log Log row.
	 */
	public function render_detail_view( array $log ): void {
		$variables    = json_decode( (string) $log['variables_json'], true );
		$email_status = $log['email_status_json'] ?? '';

		echo '<div class="wrap">';
		echo '<h1>' . esc_html__( 'Certificate Log Detail', 'alynt-certificate-generator' ) . '</h1>';
		echo '<hr class="wp-header-end" />';
		echo '<p><a class="button" href="' . esc_url( admin_url( 'admin.php?page=alynt-certificate-logs' ) ) . '">' . esc_html__( 'Back to Logs', 'alynt-certificate-generator' ) . '</a></p>';

		echo '<table class="widefat striped">';
		echo '<caption class="screen-reader-text">' . esc_html__( 'Certificate log details', 'alynt-certificate-generator' ) . '</caption>';
		echo '<tbody>';
		echo '<tr><th scope="row">' . esc_html__( 'Certificate ID', 'alynt-certificate-generator' ) . '</th><td>' . esc_html( (string) $log['certificate_id'] ) . '</td></tr>';
		echo '<tr><th scope="row">' . esc_html__( 'Template', 'alynt-certificate-generator' ) . '</th><td>' . esc_html( get_the_title( (int) $log['template_id'] ) ) . '</td></tr>';
		echo '<tr><th scope="row">' . esc_html__( 'Method', 'alynt-certificate-generator' ) . '</th><td>' . esc_html( (string) $log['method'] ) . '</td></tr>';
		echo '<tr><th scope="row">' . esc_html__( 'Generated By', 'alynt-certificate-generator' ) . '</th><td>' . esc_html( (string) $log['generated_by'] ) . '</td></tr>';
		echo '<tr><th scope="row">' . esc_html__( 'IP Address', 'alynt-certificate-generator' ) . '</th><td>' . esc_html( (string) $log['ip_address'] ) . '</td></tr>';
		echo '<tr><th scope="row">' . esc_html__( 'Created At', 'alynt-certificate-generator' ) . '</th><td>' . esc_html( (string) $log['created_at'] ) . '</td></tr>';
		echo '<tr><th scope="row">' . esc_html__( 'Email Status', 'alynt-certificate-generator' ) . '</th><td><pre>' . esc_html( (string) $email_status ) . '</pre></td></tr>';
		echo '<tr><th scope="row">' . esc_html__( 'Webhook Status', 'alynt-certificate-generator' ) . '</th><td>' . esc_html( (string) $log['webhook_status'] ) . '</td></tr>';
		echo '<tr><th scope="row">' . esc_html__( 'PDF Path', 'alynt-certificate-generator' ) . '</th><td><code>' . esc_html( (string) $log['pdf_path'] ) . '</code></td></tr>';
		echo '</tbody>';
		echo '</table>';

		if ( is_array( $variables ) ) {
			echo '<h2>' . esc_html__( 'Variables', 'alynt-certificate-generator' ) . '</h2>';
			echo '<pre>' . esc_html( wp_json_encode( $variables, JSON_PRETTY_PRINT ) ) . '</pre>';
		}

		echo '</div>';
	}
}
